2020-05-01 18:59:20,685 ERROR: Exception on /auth/register [POST] [in c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Andrew Yu\Documents\Prog\Projects\kickoff\app\auth\routes.py", line 35, in register
    return redirect(url_for('login'))
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2020-05-01 19:00:33,565 INFO: Kickoff startup [in C:\Users\Andrew Yu\Documents\Prog\Projects\kickoff\app\__init__.py:60]
2020-05-01 19:01:11,707 ERROR: Exception on /kickoff [GET] [in c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\andrew~1\envs\flask-kickoff\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Andrew Yu\Documents\Prog\Projects\kickoff\app\main\routes.py", line 30, in kickoff
    img1 = url_for('static',filename='img/'+str(player1.sofifa_id)+'.png')
AttributeError: 'NoneType' object has no attribute 'sofifa_id'
